import { access } from "node:fs/promises";
import path from "node:path";

const rootDir = process.cwd();
const requiredPaths = [
  "apps/app/index.html",
  "apps/app/app/dashboard/page.tsx",
  "apps/app/app/actions.ts",
  "apps/app/app/api/health/route.ts",
  "apps/app/app/places/page.tsx",
  "apps/app/app/hosts/page.tsx",
  "apps/app/app/experts/page.tsx",
  "apps/app/app/communities/page.tsx",
  "apps/app/app/events/page.tsx",
  "apps/app/app/proofs/page.tsx",
  "apps/app/app/profile/page.tsx",
  "apps/app/app/settings/page.tsx",
  "apps/app/components/NotificationFeed.tsx",
  "apps/app/components/SessionSwitcher.tsx",
  "apps/app/components/ProofSubmissionForm.tsx",
  "apps/app/components/ModerationQueue.tsx",
  "apps/docs/index.html",
  "apps/docs/getting-started.html",
  "apps/docs/what-is-omdala.html",
  "apps/docs/what-is-omdalat.html",
  "apps/docs/how-it-works.html",
  "apps/docs/programs.html",
  "apps/docs/roles.html",
  "apps/docs/trust-and-proof.html",
  "apps/docs/policies.html",
  "apps/docs/operator-guide.html",
  "apps/docs/styles.css",
  "apps/web/app/layout.tsx",
  "apps/web/app/page.tsx",
  "apps/web/app/about/page.tsx",
  "apps/web/app/articles/page.tsx",
  "apps/web/app/articles/[slug]/page.tsx",
  "apps/web/app/community/page.tsx",
  "apps/web/app/contact/page.tsx",
  "apps/web/app/join/page.tsx",
  "apps/web/app/life/page.tsx",
  "apps/web/app/learning/page.tsx",
  "apps/web/app/work/page.tsx",
  "apps/web/app/stay/page.tsx",
  "apps/web/app/places/[slug]/page.tsx",
  "apps/web/app/privacy/page.tsx",
  "apps/web/app/proofs/[slug]/page.tsx",
  "apps/web/app/terms/page.tsx",
  "apps/web/app/docs/page.tsx",
  "apps/web/app/docs/getting-started/page.tsx",
  "apps/web/app/docs/how-it-works/page.tsx",
  "apps/web/app/docs/faq/page.tsx",
  "apps/web/app/communities/[slug]/page.tsx",
  "apps/web/app/member/page.tsx",
  "apps/web/app/member/login/page.tsx",
  "apps/web/app/member/register/page.tsx",
  "apps/web/app/member/verify/page.tsx",
  "apps/web/index.html",
  "apps/web/next.config.js",
  "apps/web/package.json",
  "apps/web/tsconfig.json",
  "data/communities.json",
  "data/experts.json",
  "docs/REPO_BUILD_ORDER_OMDALAT.md",
  "docs/FILE_TREE_OMDALAT_V1.md",
  "packages/core/index.ts",
  "packages/types/index.ts",
  "packages/ui/index.ts",
  "services/api/index.ts",
  "services/auth/index.ts",
  "services/trust/index.ts",
  "services/matching/index.ts",
  "services/notifications/index.ts",
  "scripts/validate-i18n-data.mjs",
  "package.json"
];

for (const relativePath of requiredPaths) {
  await access(path.join(rootDir, relativePath));
}

console.log("Build preflight passed.");
