name = "omdalat-app"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
GOOGLE_CLIENT_ID = "496670862618-0kvso0cjpm66tld65lu6n8mgrgoulmn7.apps.googleusercontent.com"
NEXT_PUBLIC_APP_ORIGIN = "https://app.omdalat.com"
